### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by megakor** [skopco/powered-cache#4]
Hope you understand my english.
1. So if I enable "SSL Cache" and "Gzip" its working perfectly for me.
But I have one problem with 404 pages. If i navigate to any page which does not exist (for example https://site/sdadfasdfasdfasdf) CHROME gives me an error: ERR_CONTENT_DECODING_FAILED.
If I turn off gzip it will work fine, but i want gzip compress on my site.
2. I have cronjob which run wp-cron.php every hour. And every time it gives "Notice: Undefined index: HTTP_HOST in /home/r/admin/site/public_html/wp-content/advanced-cache.php on line 4".
`LINE 4: $config_file = WP_CONTENT_DIR . '/pc-config/config-' . $_SERVER['HTTP_HOST'];`
3. Option field "Never cache the following pages" does not working with regex or what?
```
If I put https://site/folder/page/ it working good.
If I put /folder/page/ it working good.
If I put /([^/]*)/page/ it does not working.
If I put /.*/page/ it does not working.
```

**Comment by mustafauysal** [comment]
Hi @megakor ,

Thanks for bug report.

> So if I enable "SSL Cache" and "Gzip" its working perfectly for me.
But I have one problem with 404 pages. If i navigate to any page which does not exist (for example https://site/sdadfasdfasdfasdf) CHROME gives me an error: ERR_CONTENT_DECODING_FAILED.
If I turn off gzip it will work fine, but i want gzip compress on my site.

This problem will be fixed in next version, sorry for that. Also I highly recommended gzip compression on web server (apache/nginx)

> I have cronjob which run wp-cron.php every hour. And every time it gives "Notice: Undefined index: HTTP_HOST in /home/r/admin/site/public_html/wp-content/advanced-cache.php on line 4".

`wp-cron.php` file executing via PHP? you are making http request to `wp-cron.php` address?

> Option field "Never cache the following pages" does not working with regex or what?

It seems there is a problem with regex part of functionality. I will check it out.

Thanks,

**Comment by megakor** [comment]
> wp-cron.php file executing via PHP? you are making http request to wp-cron.php address?

Yes, via PHP.

**Comment by mustafauysal** [comment]
> Yes, via PHP.
Please use don't use PHP directly for the cron.

try something like;
```
*/10 * * * * curl http://example.com/wp-cron.php?doing_wp_cron > /dev/null 2>&1
```
or you can use WP-CLI.

**Comment by mustafauysal** [comment]
Hi @megakor ,

version 1.0.1 released and these bugs fixed. So I'm closing this issue, feel free to reopen if the update doesn't work for you.
