### ISSUE TITLE
Installing on multiple servers

### ISSUE THREAD

**Issue by partounian** [skopco/powered-cache#52]
I have a setup using roots/trellis that has 2-4 servers running Nginx + PHP, then another server for the DB, and one Elasticache instance, in the past with other plugins/manually installing drop-ins I've had trouble with using Memcached or Redis cache in general, any tips to help?

Also can page caching be setup to use Redis or Memcache[d]?

**Comment by mustafauysal** [comment]
Hi @partounian,

If you are using multiple application servers, and those are not writing the cached files to a shared file system like NFS, I highly recommended using Varnish or [batcache](https://github.com/Automattic/batcache).

In order to use Batcache (relatively easy to set-up, you should consider) you need an object cache drop-in.

**Comment by partounian** [comment]
Thanks so much for the reply!

After trying various options, fastcgi on each server and Redis Cache by
Till Kruss (as a drop-in only) seems to be working pretty well. When I get
a chance I'll see if I can get better results with one of those options.

Please excuse any typos as I'm sending this message from my phone.

**Comment by partounian** [comment]
If anyone is interested, look here for an updated batcache https://github.com/partounian/100up-batcache
